### ISSUE TITLE
Block statement skipped during parsing

### ISSUE THREAD

**Issue by manuelleduc** [gemoc/ale-lang#16] opened 2018-12-07 08:45 UTC
In the code snippet below, the `xs += a::B.create();` statement is skipped during parsing.

In other words, when observing the `ExtendedClass` instance using eclipse's debug tools, the object has a single test method (as expected), which contains 7 statements (instead of the expected 8), the one missing being the `xs += a::B.create();`.

```
behavior test0;

open class A {
	
	@main
	def void test() {
		self.m := 1;
		self.ms += a::B.create();
		Sequence(a::B) xs := self.ms;
		'A'.log();
		xs.log();
		xs += a::B.create();
		'B'.log();
		xs.log();
	}
}
```

**Comment by fcoulon** [comment] 2018-12-07 09:00
Probably related to https://github.com/gemoc/ale-lang/issues/15

**Comment by manuelleduc** [comment] 2018-12-07 10:04
I am proposing the following replacement for the `visitRInsert` method in `/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/parser/visitor/AstVisitors.java` as a first step to the resolution of the issue.

Now the statement is present in the model post parsing.

Next steps: 

**1**
solving the typing error displated on eclipse:
> The feature xs is not defined

**2**
When executing the program, no element B are inserted. Consequently the to `xs.log()` are printing the same thing.

```java
@Override
		public Statement visitRInsert(RInsertContext ctx) {
			ExpressionContext left = ctx.expression(); // epxression.feature or variable?
			RExpressionContext value = ctx.rExpression();

			Statement res = null;
			if (left instanceof NavContext) {
				NavContext navCtx = (NavContext) left;
				NavigationSegmentContext navSegment = navCtx.navigationSegment();
				if (navSegment instanceof FeatureContext) {
					FeatureContext featCtx = (FeatureContext) navSegment;
					String feature = featCtx.Ident().getText();
					ExpressionContext target = navCtx.expression();
					res = ModelBuilder.singleton.buildFeatureInsert(target, feature, value.expression(), parseRes);
				}
			} else if (left instanceof VarRefContext) {
				final VarRefContext varRefCtx = (VarRefContext) left;
				final ExpressionContext target = varRefCtx;
				final String feature = varRefCtx.Ident().getText();
				final ExpressionContext valueExp = value.expression();
				res = ModelBuilder.singleton.buildFeatureInsert(target, feature, valueExp, parseRes);
			}

			parseRes.getStartPositions().put(res, ctx.start.getStartIndex());
			parseRes.getEndPositions().put(res, ctx.stop.getStopIndex());
			return res;
		}
```

**Comment by fcoulon** [comment] 2018-12-07 12:10
We need to rework this operator to manage more complex situations like:
```
    localCollection += element;
    myVariable.callOperation() += element;
    someVar.someOp().someFeature += element; // actually managed
```
I think we need a more stupid code in the parser to create a simple node in the AST and write a more complex code in the evaluator

**Comment by manuelleduc** [comment] 2018-12-10 09:07
For the record, here is another abnormal behavior of the static checking related to sequences.

The single statement of the `tmp` method returns the following error: "The feature xs is not defined".

```
behavior test0;

open class A {
	
	@main
	def void test() {
		self.m := 1;
		self.ms += a::B.create();
		Sequence(a::B) xs := self.ms;
		'A'.log();
		xs.log();
		xs += a::B.create();
		'B'.log();
		xs.log();
	}
	
	def void tmp(Sequence(a::B) xs) {
		xs += a::B.create();
	}
}
```

**Comment by fcoulon** [comment] 2018-12-11 16:49
Should be fixed by ebf55dfe087c300731f76d0c7681c797f8208fc7

**Comment by fcoulon** [comment] 2019-07-03 07:44
Can I close?

**Comment by echebbi** [comment] 2020-06-27 17:52
Can't reproduce on master @ 265f946. Closing.

**Closed by echebbi** 2020-06-27 17:52 UTC
